[package]
name = "contrack-monitor"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bpf-common = { workspace = true }
pulsar-core = { workspace = true }
log = { workspace = true }
chrono = { workspace = true, features = ["std"] }

[build-dependencies]
bpf-builder = { workspace = true }
